[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*", "https://blog.dorotheum.com/.*", "https://www.pictorem.com/.*", "https://www.oldholland.com/.*", "https://chp-art.s3-us-west-1.amazonaws.com/.*", "https://www.christies.com/.*", "https://apollo-magazine.com/.*", "https://m.media-amazon.com/.*", "https://i.guim.co.uk/.*"]

[build]
  command = "bun run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
